# 此处 namespace 来自于环境变量文件（变量名：zapp-ht）
# -- 开发配置：.env.development
# -- 生产配置：.env.production
# 静态存储不需要相关配置，直接
# 配置 PV / PVC / StorageClass
# 此处使用了 minkube 中的动态配置
# StorageClass = zero-cloud-tidb
---
# ------------------ /database/tidb/ssd
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  namespace: $KZ_NS
  name: zero-cloud-tidb
  annotations:
    storageclass.beta.kubernetes.io/is-default-class: "true"
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
provisioner: k8s.io/minikube-hostpath
reclaimPolicy: Retain
volumeBindingMode: Immediate